作業

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [1]:
import numpy as np

In [2]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
all_array = np.arange(0,21)
all_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
#2.呈上題，將以上數列取出偶數。

even_array = all_array[::2]
even_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#2.呈1題，將數列取出3的倍數。
array_3 = all_array[3::3]
array_3

array([ 3,  6,  9, 12, 15, 18])

In [6]:
array_4 = all_array[::-1]
array_4

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

In [7]:
array_5 = all_array[::-2]
array_5

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [8]:
array_6 = all_array[::-5]
array_6

array([20, 15, 10,  5,  0])

In [9]:
array_7 = all_array[10::-5]
array_7

array([10,  5,  0])