# 範例
***

# [教學目標]

* 能夠使用不同的方法初始化一個陣列
* 知道固定大小對於陣列的意義
* 了解不同的亂數陣列有什麼差異



In [ ]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/wei/.virtualenvs/py3/lib/python3.6/site-packages/numpy/__init__.py'>
1.16.1


In [ ]:
# 內建型態做轉換

import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
# 會自動轉換成範圍比較大的型態：

print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

# 也可以指定成想要的型態：

print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128


In [ ]:
# 字典型態被轉成陣列不符合期待

print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)

# 正確的寫法應該寫轉成有序的 List 再作轉換

print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

{0: 123, 1: 456}
1
[[  0 123]
 [  1 456]]
4


In [ ]:
# 從固定大小的初始值開始

print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2, 3), 9))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [ ]:
# np.zeros 和 np.empty 

print(np.zeros((2, 3)))
print(np.empty((2, 3)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 從固定大小的序列值開始

print(np.arange( 10, 30, 5 ))
print(np.linspace( 0, 2, 3 ))
print(np.logspace( 0, 2, 3 ))


[10 15 20 25]
[0. 1. 2.]
[  1.  10. 100.]


In [ ]:
## 從固定大小的亂數值開始（新版）

from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2)) #常態分布
random = rng.random((3,2)) #0~1之間的亂數
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[-0.24474896 -1.33770124 -0.10670728]
 [ 1.04809472 -1.48783473 -2.59464583]]
[[0.11597017 0.69626   ]
 [0.19672026 0.90570296]
 [0.38300972 0.37025436]]
[[0 8]
 [7 6]
 [7 3]]


In [ ]:
## 從固定大小的亂數值開始（舊版）

normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[-0.85696769 -0.03929064 -0.43855898]
 [ 0.77037149 -0.51963871 -0.25234342]]
[[0.05117243 0.44764696]
 [0.35231559 0.60465553]
 [0.38218634 0.72874085]]
[[7 2]
 [2 9]
 [5 5]]
