# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [2]:
import numpy as np

a = np.random.randint(10, size=6) 

print(a)

print('list(a): ', list(a))
print('a.tolist(): ', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print(b)

print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())



[4 0 1 2 6 9]
list(a):  [4, 0, 1, 2, 6, 9]
a.tolist():  [4, 0, 1, 2, 6, 9]
[[9 9]
 [1 7]
 [3 6]]
list(b):  [array([9, 9]), array([1, 7]), array([3, 6])]
b.tolist():  [[9, 9], [1, 7], [3, 6]]


In [12]:
'''
list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；tolist() 才能達成多層的型態轉換。
'''

'\nlist(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；tolist() 才能達成多層的型態轉換。\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [3]:
# 參考解答

import numpy as np

a = np.random.randint(10, size=6) #一維陣列

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[0 3 8 5 3 6]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [5]:
b = np.random.randint(10, size=(3,4))  #二維陣列

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[1 0 7 7]
 [4 7 0 0]
 [5 7 5 6]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [6]:
c = np.random.randint(10, size=(2,3,2)) #三維陣列

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[3 9]
  [4 1]
  [8 2]]

 [[5 2]
  [4 3]
  [9 1]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[9, 2, 4, 4, 7, 8]
[9, 2, 4, 4, 7, 8]


In [7]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[4, 8, 0, 9], [6, 3, 6, 8], [2, 4, 0, 3]]
[array([4, 8, 0, 9]), array([6, 3, 6, 8]), array([2, 4, 0, 3])]


In [8]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[5, 3], [5, 5], [9, 9]], [[9, 0], [5, 9], [2, 0]]]
[array([[5, 3],
       [5, 5],
       [9, 9]]), array([[9, 0],
       [5, 9],
       [2, 0]])]


In [9]:
## 簡單版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    
    newlist = []
    
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 2, 4, 4, 7, 8]
[[4, 8, 0, 9], [6, 3, 6, 8], [2, 4, 0, 3]]
[[[5, 3], [5, 5], [9, 9]], [[9, 0], [5, 9], [2, 0]]]


In [10]:
## 進階版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 2, 4, 4, 7, 8]
[[4, 8, 0, 9], [6, 3, 6, 8], [2, 4, 0, 3]]
[[[5, 3], [5, 5], [9, 9]], [[9, 0], [5, 9], [2, 0]]]
